'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),C=require('../public/core.js'),PNG=require('../public/apng.js'),{atomic}=require('./store.cjs');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
class RenderCache{
 constructor(dir){this.dir=dir;this.jobs=path.join(dir,'jobs');this.frames=path.join(dir,'frames');fs.mkdirSync(this.jobs,{recursive:true});fs.mkdirSync(this.frames,{recursive:true});}
 path(dir,id,ext){if(!/^[a-f0-9]{64}$/.test(id))throw Error('Invalid render ID');return path.join(dir,id+ext);}
 job(id){const file=this.path(this.jobs,id,'.json');if(fs.statSync(file).size>2000000)throw Error('Oversized render manifest');const j=JSON.parse(fs.readFileSync(file,'utf8'));if(j.id!==id)throw Error('Job identity mismatch');return j;}
 begin(project,revision,options={}){C.validate(project);const width=options.width??project.width,height=options.height??project.height,start=options.start??0,end=options.end??project.frames;for(const [v,min,max]of [[width,64,4096],[height,64,4096],[start,0,project.frames-1],[end,start+1,project.frames]])if(!Number.isInteger(v)||v<min||v>max)throw Error('Invalid render range or size');if(end-start>600)throw Error('Render batches are limited to 600 frames; split long shots into ranges');const source=sha(JSON.stringify(project)),id=sha(JSON.stringify({source,revision,width,height,start,end,version:C.VERSION}));const j={id,version:C.VERSION,source,sourceRevision:revision,width,height,start,end,fps:project.fps,frames:[]};for(let f=start;f<end;f++){const svg=C.renderSVG(project,f,{width,height}),key=sha(C.VERSION+'\n'+svg.replace(/ aria-label="[^"]*"/,''));const file=this.path(this.frames,key,'.svg');if(!fs.existsSync(file)||sha(C.VERSION+'\n'+fs.readFileSync(file,'utf8').replace(/ aria-label="[^"]*"/,''))!==key)atomic(file,svg);j.frames.push({frame:f,key});}atomic(this.path(this.jobs,id,'.json'),JSON.stringify(j));return{...j,cached:j.frames.filter(f=>this.cached(f.key)).map(f=>f.frame)};}
 cached(key){const file=this.path(this.frames,key,'.png'),meta=this.path(this.frames,key,'.json');try{const m=JSON.parse(fs.readFileSync(meta,'utf8')),b=fs.readFileSync(file);return m.key===key&&m.sha256===sha(b);}catch{return false;}}
 read(id,frame){const j=this.job(id),row=j.frames.find(x=>x.frame===frame);if(!row)throw Error('Frame is outside job');const svg=fs.readFileSync(this.path(this.frames,row.key,'.svg'),'utf8');if(sha(C.VERSION+'\n'+svg.replace(/ aria-label="[^"]*"/,''))!==row.key)throw Error('SVG cache checksum mismatch; restart the render job');return{frame,key:row.key,width:j.width,height:j.height,svg,png:this.cached(row.key)?'data:image/png;base64,'+fs.readFileSync(this.path(this.frames,row.key,'.png')).toString('base64'):null};}
 put(id,frame,data){const j=this.job(id),row=j.frames.find(x=>x.frame===frame);if(!row)throw Error('Frame is outside job');if(typeof data!=='string'||data.length>24000000||!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(data))throw Error('PNG payload required');const b=Buffer.from(data.split(',')[1],'base64'),chunks=PNG.parse(new Uint8Array(b)),v=new DataView(chunks[0].data.buffer,chunks[0].data.byteOffset,13);if(v.getUint32(0)!==j.width||v.getUint32(4)!==j.height)throw Error('PNG dimensions do not match frozen job');const file=this.path(this.frames,row.key,'.png'),tmp=file+'.tmp-'+crypto.randomBytes(4).toString('hex');try{fs.writeFileSync(tmp,b,{mode:0o600});fs.renameSync(tmp,file);}finally{try{fs.unlinkSync(tmp);}catch{}}atomic(this.path(this.frames,row.key,'.json'),JSON.stringify({key:row.key,sha256:sha(b),bytes:b.length}));return{frame,key:row.key,bytes:b.length};}
}
module.exports={RenderCache,sha};
