'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),V=require('../public/vault.js'),{BlobStore}=require('./blob-store.cjs');
function hash(s){return crypto.createHash('sha256').update(s).digest('hex');}
function encode(s){const payload=V.snapshot(s);return JSON.stringify({format:'koma.vault/2',sha256:hash(JSON.stringify(payload)),payload});}
function decode(text,blobs=null){if(Buffer.byteLength(text)>V.LIMIT*4)throw new Error('Vault file exceeds size limit');const e=JSON.parse(text);if(!['koma.vault/2','koma.vault/3'].includes(e.format)||typeof e.sha256!=='string'||hash(JSON.stringify(e.payload))!==e.sha256)throw new Error('Vault checksum mismatch');if(e.format==='koma.vault/3'){if(!blobs)throw new Error('Asset store required');return V.restore(blobs.unpack(e.payload));}return V.restore(e.payload);}
function atomic(file,text){const tmp=file+'.tmp-'+crypto.randomBytes(6).toString('hex');let fd;try{fd=fs.openSync(tmp,'wx',0o600);fs.writeFileSync(fd,text,'utf8');fs.fsyncSync(fd);fs.closeSync(fd);fd=undefined;fs.renameSync(tmp,file);try{const dir=fs.openSync(path.dirname(file),'r');try{fs.fsyncSync(dir);}finally{fs.closeSync(dir);}}catch(e){if(!['EINVAL','ENOTSUP','EISDIR','EPERM','EACCES'].includes(e.code))throw e;}}finally{if(fd!==undefined)fs.closeSync(fd);try{fs.unlinkSync(tmp);}catch(e){if(e.code!=='ENOENT')throw e;}}}
class Store{
 constructor(dir){fs.mkdirSync(dir,{recursive:true,mode:0o700});this.blobs=new BlobStore(path.join(dir,'assets'));this.file=path.join(dir,'vault-v2.json');this.backup=this.file+'.bak';this.recovery={source:'new',warning:null};}
 read(file){if(fs.statSync(file).size>V.LIMIT*4)throw new Error('Vault file too large');return decode(fs.readFileSync(file,'utf8'),this.blobs);}
 load(){if(!fs.existsSync(this.file)&&!fs.existsSync(this.backup))return null;try{const s=this.read(this.file);this.recovery={source:'primary',warning:null};return s;}catch(primary){try{const s=this.read(this.backup);this.recovery={source:'backup',warning:'Primary save could not be validated. Recovered the previous committed snapshot. Latest changes may be missing.'};return s;}catch(backup){throw new Error('Both vault copies failed. Files preserved; refusing to start with an empty project. '+primary.message+' / '+backup.message);}}}
 save(s){const payload=this.blobs.pack(V.snapshot(s)),text=JSON.stringify({format:JSON.stringify(payload).includes('"$komaBlob":')?'koma.vault/3':'koma.vault/2',sha256:hash(JSON.stringify(payload)),payload});if(fs.existsSync(this.file)){let valid=false;try{this.read(this.file);valid=true;}catch{}if(valid)atomic(this.backup,fs.readFileSync(this.file,'utf8'));}atomic(this.file,text);}
}
module.exports={Store,atomic,encode,decode};
