#!/usr/bin/env node
/* Minimal MCP stdio transport. No model calls, no arbitrary shell execution. */
'use strict';
const readline=require('node:readline');const client=require('./client.cjs');let ownedLease=null;const request=(route,body)=>client.request(route,body,ownedLease?{'X-Koma-Lease':ownedLease}:{});
const Atelier=require('../public/production/atelier.js');
const allowed=['set_param','set_exposure','set_key','remove_key','set_layer',...require('../public/plugins.js').operations.filter(x=>x!=='import_cels'),...require('../public/cinema.js').operations,...require('../public/production/engine.js').operations];
const commandSchema={type:'array',minItems:1,maxItems:128,items:{type:'object',properties:{op:{type:'string',enum:allowed}},required:['op'],additionalProperties:true}};
const tools=[
 {name:'scene_read',description:'Read revision, scene, recent operations and deterministic diagnostics. Frame numbers are zero-based. Read before editing.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true}},
 {name:'scene_preview',description:'Validate an atomic command proposal without changing the scene. Returns planId, baseRevision and a before/after diff. Operations: set_param(name,value); set_exposure(value 1..3); set_key(layer,frame,values{x,y,rotation,scaleX,scaleY,opacity,drawing},interpolation hold|linear|ease); remove_key(layer,frame); set_layer(layer,property visible|locked|name|drawing,value). Locked layers reject animation changes. Plugins: set_contact(id,layer,start,end,x,y,mode screen|ground); remove_contact(id); capture_clip(id,name,layers,start,end); apply_clip(id,start,duration,repeat,collision error|replace); delete_clip(id); set_cel_range(layer,start,end,cel assetID|null). Legacy cat ranges are inclusive. PRODUCTION prod_* ranges are END-EXCLUSIVE; consult docs/PRO-COMMANDS.md. Zero-based. Clip application bakes every integer frame of selected tracks to preserve outside samples. New image assets must be imported through local UI/CLI, not base64 in model tool arguments.',inputSchema:{type:'object',properties:{expectedRevision:{type:'integer'},commands:commandSchema},required:['expectedRevision','commands'],additionalProperties:false},annotations:{readOnlyHint:true}},
 {name:'scene_commit',description:'Apply exactly one previously inspected proposal. Use its baseRevision; stale revisions are rejected. Obtain approval for meaningful creative changes according to the host policy.',inputSchema:{type:'object',properties:{planId:{type:'string'},expectedRevision:{type:'integer'}},required:['planId','expectedRevision'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false}},
 {name:'scene_seek',description:'Show a zero-based frame in the UI so it can be inspected with Computer Use. Does not change artwork.',inputSchema:{type:'object',properties:{frame:{type:'integer',minimum:0}},required:['frame'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false}},
 {name:'scene_qa',description:'Read structural and loop-phase checks. These checks do not certify anatomy, style or cinematic quality.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true}}
];
tools.push(
 {name:'scene_plugins',description:'List current offline production plugins and their command operations. No subscriptions, model calls or external network. Production IK supports configured two-link chains; legacy Contact IK supports only cat legs. Read AGENTS.md and docs/PRODUCTION-COMMANDS.md.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true}},
 {name:'scene_checkpoint',description:'Create a persistent named checkpoint of the current project. Also increments revision and invalidates old plans.',inputSchema:{type:'object',properties:{name:{type:'string',minLength:1,maxLength:80},expectedRevision:{type:'integer',minimum:0}},required:['name','expectedRevision'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false}},
 {name:'scene_restore_checkpoint',description:'Restore a named checkpoint. Reversible through undo. Requires current revision; inspect before restoring.',inputSchema:{type:'object',properties:{id:{type:'string'},expectedRevision:{type:'integer',minimum:0}},required:['id','expectedRevision'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false}},
 {name:'scene_history',description:'Undo or redo the most recent committed scene edit; history survives local-server restart.',inputSchema:{type:'object',properties:{direction:{type:'string',enum:['undo','redo']},expectedRevision:{type:'integer',minimum:0}},required:['direction','expectedRevision'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false}}
);
tools.push(
 {name:'scene_preflight',description:'Check the current production project for blocking notes, structural problems and bounded numerical warnings. Not an artistic quality score.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true}},
 {name:'scene_render_queue',description:'List, create or pause LOCAL frozen-source render jobs. Creation does not start rendering. An open Pro Desk browser worker must run/resume the queue. PNG/WAV jobs only; no paid service. Pause stops server acceptance of new frames. Never promise background completion.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['list','create','pause']},id:{type:'string'},expectedRevision:{type:'integer',minimum:0},jobs:{type:'array',minItems:1,maxItems:32,items:{type:'object',properties:{name:{type:'string',maxLength:120},start:{type:'integer',minimum:0},end:{type:'integer',minimum:1},width:{type:'integer',minimum:64,maximum:4096},height:{type:'integer',minimum:64,maximum:4096}},required:['name','start','end','width','height'],additionalProperties:false}}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false}}
);
const scopeSchema={type:'object',properties:{shot:{type:'string'},targets:{type:'array',items:{type:'string'},minItems:1},related:{type:'array',items:{type:'string'}},protect:{type:'array',items:{type:'string'}},start:{type:'integer',minimum:0},end:{type:'integer',minimum:1}},required:['shot','targets'],additionalProperties:false};
tools.push(
 {name:'atelier_read',description:'Read drawing provenance, color-region validity, named parts/anchors, references and stage approvals. With geometry=true returns editable native geometry for one asset; embedded raster bytes are redacted. Explicit version required.',inputSchema:{type:'object',properties:{expectedRevision:{type:'integer',minimum:0},asset:{type:'string'},shot:{type:'string'},geometry:{type:'boolean'}},required:['expectedRevision'],additionalProperties:false},annotations:{readOnlyHint:true}},
 {name:'atelier_edit_preview',description:'Propose typed drawing, paint, pose, reference or pipeline operations. Does not commit. Optional scope rejects protected/unauthorized dependencies and evaluated changes outside the end-exclusive range. Region split/merge remains reviewable, not silently recolored. Obtain approval under host policy before scene_commit.',inputSchema:{type:'object',properties:{expectedRevision:{type:'integer',minimum:0},commands:{type:'array',minItems:1,maxItems:128,items:{oneOf:Object.values(Atelier.schemas)}},scope:scopeSchema},required:['expectedRevision','commands'],additionalProperties:false},annotations:{readOnlyHint:true}},
 {name:'scene_render_image',description:'Return a real PNG image plus revision, source SHA-256 and image-to-document coordinate mapping. Requires an active browser on THIS local server. Modes include rough/line/flat/shadow/highlight/correction/composite and plan diff. No model call. A timeout is an error, not a completed render. Pixel statistics apply to sampled output resolution only.',inputSchema:{type:'object',properties:{expectedRevision:{type:'integer',minimum:0},frame:{type:'integer',minimum:0},asset:{type:'string'},mode:{type:'string',enum:['composite','line','flat','rough','correction','shadow','highlight','regions','diff']},width:{type:'integer',minimum:32,maximum:2048},height:{type:'integer',minimum:32,maximum:2048},crop:{type:'array',items:{type:'number'},minItems:4,maxItems:4},allowedBox:{type:'array',items:{type:'number'},minItems:4,maxItems:4},planId:{type:'string'},onion:{type:'boolean'}},required:['expectedRevision'],additionalProperties:false},annotations:{readOnlyHint:true}},
 {name:'scene_edit_lease',description:'Acquire/renew/release a short project-wide edit lease for human/agent handoff. Read and preview stay available. While held, other editors cannot commit, undo, import or restore. Lease expires after 5..120 seconds; no credentials are saved in project data. Re-read revision after acquisition.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['status','acquire','renew','release']},owner:{type:'string',maxLength:100},purpose:{type:'string',maxLength:200},seconds:{type:'number',minimum:5,maximum:120}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false}},
 {name:'atelier_command_schema',description:'Return bounded formal command schemas, valid drawing planes and review-stage dependencies. Complements the older generic prod_* command interface.',inputSchema:{type:'object',properties:{operation:{type:'string',enum:Atelier.operations}},additionalProperties:false},annotations:{readOnlyHint:true}}
);
const instructions='Production projects use prod_* commands only. Read AGENTS.md and docs/PRODUCTION-COMMANDS.md for the complete schema. Production frame ranges are END-EXCLUSIVE; all frame numbers are zero-based. Assets are shared; duplicate a drawing before a frame-local edit. Transform controls and two-link IK are deterministic, not image generation. Never place embedded image/audio bytes in tool arguments; use the local UI or file-import CLI. In cinema mode use cinema_* commands only. cinema_set_camera(shot,keys[{frame,values{x,y,zoom,rotation},ease}]); cinema_set_layer(shot,layer,property,value); cinema_set_exposure(shot,layer,hold); cinema_set_effect(shot,effect,property enabled|amount,value). Shot ranges and effect ranges are END-EXCLUSIVE; old cat-plugin ranges remain inclusive. These are different contracts. Read scene_read first. Propose bounded edits using scene_preview, inspect the diff, then scene_commit with its baseRevision. Use scene_render_image for revision-bound PNGs and explicit coordinate mappings. Computer Use and MCP share the same project. Use scene_edit_lease for human/agent handoff. atelier_edit_preview exposes formal native drawing/paint/workflow schemas; scene_seek supports visual UI review. Frame indexes are zero-based. Do not unlock protected layers without permission. No image model is connected; never claim AI redraw or aesthetic QA occurred. Forbid arbitrary code, shell commands and outbound network requests in scene data.';
function redact(v){if(typeof v==='string'&&/^data:(image|audio)\//.test(v))return '[embedded media '+v.length+' bytes; use asset ID]';if(Array.isArray(v))return v.map(redact);if(v&&typeof v==='object'){const o={};for(const [k,x]of Object.entries(v))o[k]=redact(x);return o;}return v;}
async function dispatch(m){
 if(m.method==='initialize')return {protocolVersion:['2025-06-18','2025-11-25'].includes(m.params?.protocolVersion)?m.params.protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'koma-studio',version:require('../public/core.js').VERSION},instructions};
 if(m.method==='ping')return {};
 if(m.method==='tools/list')return {tools};
 if(m.method==='tools/call'){
  try{const a=m.params?.arguments||{},name=m.params?.name;let value;
   if(name==='atelier_command_schema'){value=a.operation?Atelier.schemas[a.operation]:{schemas:Atelier.schemas,planes:Atelier.PLANES,stages:Atelier.STAGES};}
   else if(name==='atelier_read'){value=await request('/api/atelier/read',a);}
   else if(name==='atelier_edit_preview'){if(!Array.isArray(a.commands))throw Error('Commands required');for(const c of a.commands){if(!Atelier.schemas[c.op])throw Error('Unknown Atelier command');Atelier.validateValue(c,Atelier.schemas[c.op]);}if(JSON.stringify(a.commands).includes('data:image/'))throw Error('Import image files through local UI');value=await request('/api/preview',a);}
   else if(name==='scene_render_image'){const result=await request('/api/atelier/render',a),metadata={...result.metadata,statistics:result.stats,verification:result.verification};return {content:[{type:'text',text:JSON.stringify(metadata)},{type:'image',mimeType:'image/png',data:result.image.data}],structuredContent:metadata};}
   else if(name==='scene_edit_lease'){
    if(a.action==='status')value=await request('/api/edit-lease');
    else if(a.action==='acquire'){if(ownedLease)throw Error('This agent already owns a lease');const r=await request('/api/edit-lease/acquire',{owner:(a.owner||'Codex')+' / MCP '+process.pid,purpose:a.purpose||'structured authoring',seconds:a.seconds||45});ownedLease=r.lease;delete r.lease;value=r;}
    else if(a.action==='renew'){if(!ownedLease)throw Error('Acquire a lease first');value=await request('/api/edit-lease/renew',{lease:ownedLease,seconds:a.seconds||45});}
    else if(a.action==='release'){if(!ownedLease)throw Error('No owned lease');value=await request('/api/edit-lease/release',{lease:ownedLease});ownedLease=null;}
    else throw Error('Unknown lease action');
   }
   else if(name==='scene_read'){value=await request('/api/state');for(const l of value.project.layers)if(l.data){l.assetBytes=l.data.length;delete l.data;}for(const l of value.project.layers)if(l.cels)for(const asset of l.cels){asset.assetBytes=asset.data.length;delete asset.data;}if(value.project.cinema)for(const a of value.project.cinema.assets)if(a.data){a.assetBytes=a.data.length;delete a.data;}value.project.patches=value.project.patches.map(p=>({frame:p.frame,source:p.source,baseRevision:p.baseRevision,embeddedImages:true}));}
   else if(name==='scene_preview'){if(!Array.isArray(a.commands)||a.commands.some(c=>!allowed.includes(c.op)))throw new Error('Unsupported MCP command');if(JSON.stringify(a.commands).includes('data:image/')||JSON.stringify(a.commands).includes('data:audio/'))throw new Error('Import media through the local file workflow; do not send embedded bytes');value=await request('/api/preview',a);}
   else if(name==='scene_commit')value=await request('/api/commit',a);
   else if(name==='scene_seek')value=await request('/api/view',a);
   else if(name==='scene_qa')value=await request('/api/qa');
   else if(name==='scene_preflight')value=await request('/api/preflight');
   else if(name==='scene_render_queue'){if(a.action==='list')value=await request('/api/queue/list');else if(a.action==='create')value=await request('/api/queue/create',{expectedRevision:a.expectedRevision,jobs:a.jobs});else if(a.action==='pause')value=await request('/api/queue/pause',{id:a.id});else throw Error('Unsupported queue action');}
   else if(name==='scene_plugins')value=await request('/api/plugins');
   else if(name==='scene_checkpoint')value=await request('/api/checkpoint',a);
   else if(name==='scene_restore_checkpoint')value=await request('/api/restore-checkpoint',a);
   else if(name==='scene_history'){if(!['undo','redo'].includes(a.direction))throw new Error('Invalid history direction');value=await request('/api/'+a.direction,{expectedRevision:a.expectedRevision});}
   else throw new Error('Unknown tool');
   return {content:[{type:'text',text:JSON.stringify(redact(value))}]};
  }catch(e){return {content:[{type:'text',text:e.message}],isError:true};}
 }
 const e=new Error('Method not found');e.code=-32601;throw e;
}
const rl=readline.createInterface({input:process.stdin,crlfDelay:Infinity});
let chain=Promise.resolve();
rl.on('line',line=>{chain=chain.then(async()=>{if(!line.trim())return;let m;try{m=JSON.parse(line);}catch{process.stdout.write(JSON.stringify({jsonrpc:'2.0',id:null,error:{code:-32700,message:'Parse error'}})+'\n');return;}if(m.id===undefined)return;try{const result=await dispatch(m);process.stdout.write(JSON.stringify({jsonrpc:'2.0',id:m.id,result})+'\n');}catch(e){process.stdout.write(JSON.stringify({jsonrpc:'2.0',id:m.id,error:{code:e.code||-32603,message:e.message}})+'\n');}});});
